#%%
import os
import numpy as np
import re

with open("test.coe", "w") as coe_file:
  coe_file.write(
  "\n".join(["; This is an autogenerated file",
             "memory_initialization_radix=16;",
             "memory_initialization_vector=\n"])
  )

  matrix = np.random.randint(9000000000000000000, size=(8, 8), dtype="int64")

  # print(matrix)

  for row in matrix:
    for num in row:
      coe_file.write("0x" + format(num, '016x') + ",\n")

with open("test.coe", "r") as coe_file:
  coe_file_data = coe_file.read()
  coe_file_data = re.sub(r',\n$', r';\n', coe_file_data)

with open("test.coe", "w") as coe_file:
  coe_file.write(coe_file_data)